# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 https://cmadison-projects.github.io/
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Chris Madison
  url:               https://twitter.com/chrismad26
  email:             cmadison@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
